#!/usr/bin/env bash
shopt -s extglob

ZAL_VERSION="1.10"
ZIMBRA_VERSION=$(sudo su - zimbra -c "zmcontrol -v" | tr -d '\n' | sed -r 's/.* ([0-9\.]+[0-9]).*/\1/')



ZAL_VERSION_EXTENDED="1.10.2"
#if [ -e "/usr/share/openzal/${ZAL_VERSION}/${ZIMBRA_VERSION}/zal.jar" ]; then
    cd extension && ant
    echo "  Downloading the correct ZAL Version (${ZAL_VERSION_EXTENDED} for zimbra ${ZIMBRA_VERSION})..."
    wget "https://openzal.org/${ZAL_VERSION}/zal-${ZAL_VERSION_EXTENDED}-${ZIMBRA_VERSION}.jar" -O "lib/zal-${ZAL_VERSION_EXTENDED}-${ZIMBRA_VERSION}.jar"
    echo "  Installing files..."
    mkdir -p /opt/zimbra/lib/ext/universalDialerExt
    rm /opt/zimbra/lib/ext/universalDialerExt/*
    cp "lib/zal-${ZAL_VERSION_EXTENDED}-${ZIMBRA_VERSION}.jar" /opt/zimbra/lib/ext/universalDialerExt/
    cp "universal-dialer-extension.jar" /opt/zimbra/lib/ext/universalDialerExt/
    cp "lib/asterisk-java-1.0.0-m1.jar" /opt/zimbra/lib/ext/universalDialerExt/
#    echo -n "  Creating zal link..."
#    sudo ln -s /usr/share/openzal/1.10/8.0.9/zal.jar /opt/zimbra/lib/ext/universalDialerExt/zal.jar
#    echo " DONE"
#else
#    echo "  Zal not found. Exiting..."
#fi